### ISSUE TITLE
TypeError: src.replace is not a function :disappointed:

### ISSUE THREAD

**Issue by michalskuza** [substack/highlight-bash-syntax#1]
I ran an example from **readme.md**  (on Windows 7) and got this error:

```
> console.log(highlight(src))
TypeError: src.replace is not a function
    at module.exports (C:\Users\ms66531\Desktop\testing-packages-nodejs\node_mod
ules\highlight-bash-syntax\index.js:16:27)
    at repl:1:13
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:212:10)
    at REPLServer.Interface._line (readline.js:551:8)
```

**Comment by substack** [comment]
Sorry about that. Fixed in 1.1.1.
